// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/chekrzk/ufanet-home-manager/api-gateway/internal/models/domain"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// AddWorker provides a mock function with given fields: ctx, actor, command
func (_m *Client) AddWorker(ctx context.Context, actor domain.AuthContext, command domain.AddWorker) (domain.Worker, error) {
	ret := _m.Called(ctx, actor, command)

	if len(ret) == 0 {
		panic("no return value specified for AddWorker")
	}

	var r0 domain.Worker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.AddWorker) (domain.Worker, error)); ok {
		return rf(ctx, actor, command)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.AddWorker) domain.Worker); ok {
		r0 = rf(ctx, actor, command)
	} else {
		r0 = ret.Get(0).(domain.Worker)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AuthContext, domain.AddWorker) error); ok {
		r1 = rf(ctx, actor, command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListWorkerAvailability provides a mock function with given fields: ctx, actor, filter
func (_m *Client) ListWorkerAvailability(ctx context.Context, actor domain.AuthContext, filter domain.WorkerAvailabilityFilter) ([]domain.WorkerAvailability, error) {
	ret := _m.Called(ctx, actor, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkerAvailability")
	}

	var r0 []domain.WorkerAvailability
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.WorkerAvailabilityFilter) ([]domain.WorkerAvailability, error)); ok {
		return rf(ctx, actor, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.WorkerAvailabilityFilter) []domain.WorkerAvailability); ok {
		r0 = rf(ctx, actor, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.WorkerAvailability)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AuthContext, domain.WorkerAvailabilityFilter) error); ok {
		r1 = rf(ctx, actor, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListWorkers provides a mock function with given fields: ctx, actor, houseID
func (_m *Client) ListWorkers(ctx context.Context, actor domain.AuthContext, houseID string) ([]domain.Worker, error) {
	ret := _m.Called(ctx, actor, houseID)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkers")
	}

	var r0 []domain.Worker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, string) ([]domain.Worker, error)); ok {
		return rf(ctx, actor, houseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, string) []domain.Worker); ok {
		r0 = rf(ctx, actor, houseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Worker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AuthContext, string) error); ok {
		r1 = rf(ctx, actor, houseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Me provides a mock function with given fields: ctx, actor
func (_m *Client) Me(ctx context.Context, actor domain.AuthContext) (domain.User, error) {
	ret := _m.Called(ctx, actor)

	if len(ret) == 0 {
		panic("no return value specified for Me")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext) (domain.User, error)); ok {
		return rf(ctx, actor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext) domain.User); ok {
		r0 = rf(ctx, actor)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AuthContext) error); ok {
		r1 = rf(ctx, actor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetWorkerAvailability provides a mock function with given fields: ctx, actor, command
func (_m *Client) SetWorkerAvailability(ctx context.Context, actor domain.AuthContext, command domain.SetWorkerAvailability) (domain.WorkerAvailability, error) {
	ret := _m.Called(ctx, actor, command)

	if len(ret) == 0 {
		panic("no return value specified for SetWorkerAvailability")
	}

	var r0 domain.WorkerAvailability
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.SetWorkerAvailability) (domain.WorkerAvailability, error)); ok {
		return rf(ctx, actor, command)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.SetWorkerAvailability) domain.WorkerAvailability); ok {
		r0 = rf(ctx, actor, command)
	} else {
		r0 = ret.Get(0).(domain.WorkerAvailability)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AuthContext, domain.SetWorkerAvailability) error); ok {
		r1 = rf(ctx, actor, command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, actor, command
func (_m *Client) Update(ctx context.Context, actor domain.AuthContext, command domain.UpdateProfile) (domain.User, error) {
	ret := _m.Called(ctx, actor, command)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.UpdateProfile) (domain.User, error)); ok {
		return rf(ctx, actor, command)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.UpdateProfile) domain.User); ok {
		r0 = rf(ctx, actor, command)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AuthContext, domain.UpdateProfile) error); ok {
		r1 = rf(ctx, actor, command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
