// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/chekrzk/ufanet-home-manager/profile-service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// ProfileRepository is an autogenerated mock type for the ProfileRepository type
type ProfileRepository struct {
	mock.Mock
}

// CreateWorker provides a mock function with given fields: ctx, worker
func (_m *ProfileRepository) CreateWorker(ctx context.Context, worker *models.Worker) error {
	ret := _m.Called(ctx, worker)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorker")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Worker) error); ok {
		r0 = rf(ctx, worker)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindProfile provides a mock function with given fields: ctx, userID
func (_m *ProfileRepository) FindProfile(ctx context.Context, userID string) (models.Profile, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for FindProfile")
	}

	var r0 models.Profile
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.Profile, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.Profile); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(models.Profile)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListWorkerAvailability provides a mock function with given fields: ctx, filter
func (_m *ProfileRepository) ListWorkerAvailability(ctx context.Context, filter models.ListWorkerAvailabilityFilter) ([]models.WorkerAvailability, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkerAvailability")
	}

	var r0 []models.WorkerAvailability
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ListWorkerAvailabilityFilter) ([]models.WorkerAvailability, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.ListWorkerAvailabilityFilter) []models.WorkerAvailability); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.WorkerAvailability)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.ListWorkerAvailabilityFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListWorkers provides a mock function with given fields: ctx, houseID
func (_m *ProfileRepository) ListWorkers(ctx context.Context, houseID string) ([]models.Worker, error) {
	ret := _m.Called(ctx, houseID)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkers")
	}

	var r0 []models.Worker
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]models.Worker, error)); ok {
		return rf(ctx, houseID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []models.Worker); ok {
		r0 = rf(ctx, houseID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Worker)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, houseID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveProfile provides a mock function with given fields: ctx, profile
func (_m *ProfileRepository) SaveProfile(ctx context.Context, profile *models.Profile) error {
	ret := _m.Called(ctx, profile)

	if len(ret) == 0 {
		panic("no return value specified for SaveProfile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Profile) error); ok {
		r0 = rf(ctx, profile)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveWorkerAvailability provides a mock function with given fields: ctx, availability
func (_m *ProfileRepository) SaveWorkerAvailability(ctx context.Context, availability *models.WorkerAvailability) error {
	ret := _m.Called(ctx, availability)

	if len(ret) == 0 {
		panic("no return value specified for SaveWorkerAvailability")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.WorkerAvailability) error); ok {
		r0 = rf(ctx, availability)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProfileRepository creates a new instance of ProfileRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProfileRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProfileRepository {
	mock := &ProfileRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
