// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/chekrzk/ufanet-home-manager/notification-service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// DeviceRepository is an autogenerated mock type for the DeviceRepository type
type DeviceRepository struct {
	mock.Mock
}

// CreateNotification provides a mock function with given fields: ctx, notification
func (_m *DeviceRepository) CreateNotification(ctx context.Context, notification *models.Notification) error {
	ret := _m.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Notification) error); ok {
		r0 = rf(ctx, notification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteDevice provides a mock function with given fields: ctx, userID, token
func (_m *DeviceRepository) DeleteDevice(ctx context.Context, userID string, token string) error {
	ret := _m.Called(ctx, userID, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDevice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListNotifications provides a mock function with given fields: ctx, command
func (_m *DeviceRepository) ListNotifications(ctx context.Context, command models.ListNotificationsCommand) ([]models.Notification, int64, error) {
	ret := _m.Called(ctx, command)

	if len(ret) == 0 {
		panic("no return value specified for ListNotifications")
	}

	var r0 []models.Notification
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ListNotificationsCommand) ([]models.Notification, int64, error)); ok {
		return rf(ctx, command)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.ListNotificationsCommand) []models.Notification); ok {
		r0 = rf(ctx, command)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.ListNotificationsCommand) int64); ok {
		r1 = rf(ctx, command)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, models.ListNotificationsCommand) error); ok {
		r2 = rf(ctx, command)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MarkRead provides a mock function with given fields: ctx, userID, notificationID
func (_m *DeviceRepository) MarkRead(ctx context.Context, userID string, notificationID string) error {
	ret := _m.Called(ctx, userID, notificationID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, notificationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveDevice provides a mock function with given fields: ctx, device
func (_m *DeviceRepository) SaveDevice(ctx context.Context, device *models.Device) error {
	ret := _m.Called(ctx, device)

	if len(ret) == 0 {
		panic("no return value specified for SaveDevice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Device) error); ok {
		r0 = rf(ctx, device)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDeviceRepository creates a new instance of DeviceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDeviceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DeviceRepository {
	mock := &DeviceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
