// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/chekrzk/ufanet-home-manager/api-gateway/internal/models/domain"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, author, command
func (_m *Service) Create(ctx context.Context, author domain.AuthContext, command domain.CreateNews) (domain.News, error) {
	ret := _m.Called(ctx, author, command)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.News
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.CreateNews) (domain.News, error)); ok {
		return rf(ctx, author, command)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.CreateNews) domain.News); ok {
		r0 = rf(ctx, author, command)
	} else {
		r0 = ret.Get(0).(domain.News)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AuthContext, domain.CreateNews) error); ok {
		r1 = rf(ctx, author, command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, actor, filter
func (_m *Service) List(ctx context.Context, actor domain.AuthContext, filter domain.NewsFilter) (domain.Page[domain.News], error) {
	ret := _m.Called(ctx, actor, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 domain.Page[domain.News]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.NewsFilter) (domain.Page[domain.News], error)); ok {
		return rf(ctx, actor, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.NewsFilter) domain.Page[domain.News]); ok {
		r0 = rf(ctx, actor, filter)
	} else {
		r0 = ret.Get(0).(domain.Page[domain.News])
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AuthContext, domain.NewsFilter) error); ok {
		r1 = rf(ctx, actor, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
