// Code generated by mockery-compatible test helper. DO NOT EDIT BY HAND.

package mocks

import (
	"context"

	"github.com/chekrzk/ufanet-home-manager/api-gateway/internal/models/domain"
	"github.com/stretchr/testify/mock"
)

type Client struct {
	mock.Mock
}

func (m *Client) List(ctx context.Context, actor domain.AuthContext, filter domain.NewsFilter) (domain.Page[domain.News], error) {
	ret := m.Called(ctx, actor, filter)
	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 domain.Page[domain.News]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.NewsFilter) (domain.Page[domain.News], error)); ok {
		return rf(ctx, actor, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.NewsFilter) domain.Page[domain.News]); ok {
		r0 = rf(ctx, actor, filter)
	} else {
		r0 = ret.Get(0).(domain.Page[domain.News])
	}
	if rf, ok := ret.Get(1).(func(context.Context, domain.AuthContext, domain.NewsFilter) error); ok {
		r1 = rf(ctx, actor, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func (m *Client) Create(ctx context.Context, author domain.AuthContext, command domain.CreateNews) (domain.News, error) {
	ret := m.Called(ctx, author, command)
	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.News
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.CreateNews) (domain.News, error)); ok {
		return rf(ctx, author, command)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.CreateNews) domain.News); ok {
		r0 = rf(ctx, author, command)
	} else {
		r0 = ret.Get(0).(domain.News)
	}
	if rf, ok := ret.Get(1).(func(context.Context, domain.AuthContext, domain.CreateNews) error); ok {
		r1 = rf(ctx, author, command)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	m := &Client{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
