// Code generated by mockery-compatible test helper. DO NOT EDIT BY HAND.

package mocks

import (
	"context"

	"github.com/chekrzk/ufanet-home-manager/api-gateway/internal/models/domain"
	"github.com/stretchr/testify/mock"
)

type Service struct {
	mock.Mock
}

func (m *Service) Me(ctx context.Context, actor domain.AuthContext) (domain.User, error) {
	ret := m.Called(ctx, actor)
	if len(ret) == 0 {
		panic("no return value specified for Me")
	}
	return ret.Get(0).(domain.User), ret.Error(1)
}

func (m *Service) Update(ctx context.Context, actor domain.AuthContext, command domain.UpdateProfile) (domain.User, error) {
	ret := m.Called(ctx, actor, command)
	if len(ret) == 0 {
		panic("no return value specified for Update")
	}
	return ret.Get(0).(domain.User), ret.Error(1)
}

func (m *Service) AddWorker(ctx context.Context, actor domain.AuthContext, command domain.AddWorker) (domain.Worker, error) {
	ret := m.Called(ctx, actor, command)
	if len(ret) == 0 {
		panic("no return value specified for AddWorker")
	}
	return ret.Get(0).(domain.Worker), ret.Error(1)
}

func (m *Service) ListWorkers(ctx context.Context, actor domain.AuthContext, houseID string) ([]domain.Worker, error) {
	ret := m.Called(ctx, actor, houseID)
	if len(ret) == 0 {
		panic("no return value specified for ListWorkers")
	}
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).([]domain.Worker), ret.Error(1)
}

func (m *Service) SetWorkerAvailability(ctx context.Context, actor domain.AuthContext, command domain.SetWorkerAvailability) (domain.WorkerAvailability, error) {
	ret := m.Called(ctx, actor, command)
	if len(ret) == 0 {
		panic("no return value specified for SetWorkerAvailability")
	}
	return ret.Get(0).(domain.WorkerAvailability), ret.Error(1)
}

func (m *Service) ListWorkerAvailability(ctx context.Context, actor domain.AuthContext, filter domain.WorkerAvailabilityFilter) ([]domain.WorkerAvailability, error) {
	ret := m.Called(ctx, actor, filter)
	if len(ret) == 0 {
		panic("no return value specified for ListWorkerAvailability")
	}
	if ret.Get(0) == nil {
		return nil, ret.Error(1)
	}
	return ret.Get(0).([]domain.WorkerAvailability), ret.Error(1)
}

func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	m := &Service{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}
