// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/chekrzk/ufanet-home-manager/api-gateway/internal/models/domain"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// AddComment provides a mock function with given fields: ctx, actor, requestID, command
func (_m *Client) AddComment(ctx context.Context, actor domain.AuthContext, requestID string, command domain.AddRequestComment) error {
	ret := _m.Called(ctx, actor, requestID, command)

	if len(ret) == 0 {
		panic("no return value specified for AddComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, string, domain.AddRequestComment) error); ok {
		r0 = rf(ctx, actor, requestID, command)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, actor, command
func (_m *Client) Create(ctx context.Context, actor domain.AuthContext, command domain.CreateRequest) (domain.Request, error) {
	ret := _m.Called(ctx, actor, command)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.CreateRequest) (domain.Request, error)); ok {
		return rf(ctx, actor, command)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.CreateRequest) domain.Request); ok {
		r0 = rf(ctx, actor, command)
	} else {
		r0 = ret.Get(0).(domain.Request)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AuthContext, domain.CreateRequest) error); ok {
		r1 = rf(ctx, actor, command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: ctx, actor, requestID
func (_m *Client) Get(ctx context.Context, actor domain.AuthContext, requestID string) (domain.Request, error) {
	ret := _m.Called(ctx, actor, requestID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, string) (domain.Request, error)); ok {
		return rf(ctx, actor, requestID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, string) domain.Request); ok {
		r0 = rf(ctx, actor, requestID)
	} else {
		r0 = ret.Get(0).(domain.Request)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AuthContext, string) error); ok {
		r1 = rf(ctx, actor, requestID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, actor, page
func (_m *Client) List(ctx context.Context, actor domain.AuthContext, page domain.Pagination) (domain.Page[domain.Request], error) {
	ret := _m.Called(ctx, actor, page)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 domain.Page[domain.Request]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.Pagination) (domain.Page[domain.Request], error)); ok {
		return rf(ctx, actor, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.Pagination) domain.Page[domain.Request]); ok {
		r0 = rf(ctx, actor, page)
	} else {
		r0 = ret.Get(0).(domain.Page[domain.Request])
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AuthContext, domain.Pagination) error); ok {
		r1 = rf(ctx, actor, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, actor, requestID, command
func (_m *Client) UpdateStatus(ctx context.Context, actor domain.AuthContext, requestID string, command domain.UpdateRequestStatus) (domain.Request, error) {
	ret := _m.Called(ctx, actor, requestID, command)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 domain.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, string, domain.UpdateRequestStatus) (domain.Request, error)); ok {
		return rf(ctx, actor, requestID, command)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, string, domain.UpdateRequestStatus) domain.Request); ok {
		r0 = rf(ctx, actor, requestID, command)
	} else {
		r0 = ret.Get(0).(domain.Request)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AuthContext, string, domain.UpdateRequestStatus) error); ok {
		r1 = rf(ctx, actor, requestID, command)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
