// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/chekrzk/ufanet-home-manager/requests-service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// NotificationPublisher is an autogenerated mock type for the NotificationPublisher type
type NotificationPublisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, event
func (_m *NotificationPublisher) Publish(ctx context.Context, event models.NotificationEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, models.NotificationEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationPublisher creates a new instance of NotificationPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationPublisher {
	mock := &NotificationPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
