// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/chekrzk/ufanet-home-manager/requests-service/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// RequestRepository is an autogenerated mock type for the RequestRepository type
type RequestRepository struct {
	mock.Mock
}

// AddComment provides a mock function with given fields: ctx, comment
func (_m *RequestRepository) AddComment(ctx context.Context, comment *models.RequestComment) error {
	ret := _m.Called(ctx, comment)

	if len(ret) == 0 {
		panic("no return value specified for AddComment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.RequestComment) error); ok {
		r0 = rf(ctx, comment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, request
func (_m *RequestRepository) Create(ctx context.Context, request *models.MaintenanceRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.MaintenanceRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *RequestRepository) FindByID(ctx context.Context, id string) (models.MaintenanceRequest, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 models.MaintenanceRequest
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (models.MaintenanceRequest, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) models.MaintenanceRequest); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(models.MaintenanceRequest)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, filter
func (_m *RequestRepository) List(ctx context.Context, filter models.ListRequestsFilter) ([]models.MaintenanceRequest, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.MaintenanceRequest
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, models.ListRequestsFilter) ([]models.MaintenanceRequest, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.ListRequestsFilter) []models.MaintenanceRequest); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.MaintenanceRequest)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.ListRequestsFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, models.ListRequestsFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Save provides a mock function with given fields: ctx, request
func (_m *RequestRepository) Save(ctx context.Context, request *models.MaintenanceRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.MaintenanceRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRequestRepository creates a new instance of RequestRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRequestRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RequestRepository {
	mock := &RequestRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
