// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/chekrzk/ufanet-home-manager/api-gateway/internal/models/domain"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// List provides a mock function with given fields: ctx, actor, page
func (_m *Client) List(ctx context.Context, actor domain.AuthContext, page domain.Pagination) (domain.Page[domain.Notification], error) {
	ret := _m.Called(ctx, actor, page)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 domain.Page[domain.Notification]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.Pagination) (domain.Page[domain.Notification], error)); ok {
		return rf(ctx, actor, page)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.Pagination) domain.Page[domain.Notification]); ok {
		r0 = rf(ctx, actor, page)
	} else {
		r0 = ret.Get(0).(domain.Page[domain.Notification])
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.AuthContext, domain.Pagination) error); ok {
		r1 = rf(ctx, actor, page)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkRead provides a mock function with given fields: ctx, actor, notificationID
func (_m *Client) MarkRead(ctx context.Context, actor domain.AuthContext, notificationID string) error {
	ret := _m.Called(ctx, actor, notificationID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, string) error); ok {
		r0 = rf(ctx, actor, notificationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegisterDevice provides a mock function with given fields: ctx, actor, device
func (_m *Client) RegisterDevice(ctx context.Context, actor domain.AuthContext, device domain.RegisterDevice) error {
	ret := _m.Called(ctx, actor, device)

	if len(ret) == 0 {
		panic("no return value specified for RegisterDevice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.RegisterDevice) error); ok {
		r0 = rf(ctx, actor, device)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UnregisterDevice provides a mock function with given fields: ctx, actor, device
func (_m *Client) UnregisterDevice(ctx context.Context, actor domain.AuthContext, device domain.UnregisterDevice) error {
	ret := _m.Called(ctx, actor, device)

	if len(ret) == 0 {
		panic("no return value specified for UnregisterDevice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.AuthContext, domain.UnregisterDevice) error); ok {
		r0 = rf(ctx, actor, device)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
